// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huxevwknorxeaqhmcttp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1eGV2d2tub3J4ZWFxaG1jdHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTUwNzUsImV4cCI6MjA3MjA5MTA3NX0.cAGMzxG277tfoldaj27VU4A4fz7gsEv7TuWVTbu04nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});